# Generated by Django 5.2.8 on 2025-11-13 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_iso', models.CharField(max_length=3, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Aeropuerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_iata', models.CharField(max_length=3, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aeropuertos', to='vuelos.pais')),
            ],
            options={
                'ordering': ['codigo_iata'],
            },
        ),
        migrations.CreateModel(
            name='Aerolinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo_iata', models.CharField(blank=True, max_length=3, null=True)),
                ('anio_fundacion', models.PositiveIntegerField(blank=True, null=True)),
                ('aeropuertos', models.ManyToManyField(blank=True, related_name='aerolineas', to='vuelos.aeropuerto')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aerolineas', to='vuelos.pais')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
